---

- name: Install php
  sudo: yes
  apt: name=php5-fpm state=installed install_recommends=yes update-cache=yes

- name: Install php
  sudo: yes
  apt: name="{{item}}" state=present
  with_items:
     - nginx
     - php5-fpm
     - php-apc
     - php5-cli
     - php5-common
     - php5-dbg
     - php5-gd
     - php5-memcache
     - php5-mcrypt
     - php5-dev
     - php5-xsl
     - php5-mysql
     - php5-curl